apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-qksh
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/dc-metro-map-qksh@sha256:b3d01949ff8c5a185a17b40474db43fe8a82da8243c71a99570baa2c7b10ebb1
        name: my-nodejs
        resources: {}
status: {}
